language: python

python:
- "3.5"

compiler: 
- gcc

before_install:
- sudo apt-get update

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda install --yes numpy scipy 
- conda install --yes scikit-image
- conda install -c https://conda.anaconda.org/memex opencv
- conda install -c https://conda.anaconda.org/dgursoy pywavelets
- conda config --add channels dgursoy
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-image opencv pywavelets -y
- source activate test-environment
- python setup.py install

script: python run.py